### ISSUE TITLE
Sanitizing money field bug

### ISSUE THREAD

**Issue by YourMark** [WebDevStudios/CMB2#177] opened 2015-02-08 17:10 UTC
If the text_money field is used and you fill in a value like 10, the value is saved as 10.00 in the database. If you save the post again, the field is updated to 1.000.00.

I think this is because of the thousand separator being saved in the DB. Maybe it's better to save money as a float in the DB and use money_format() in stead of number_format_i18n for displaying purposes. I guess this is bound to cause trouble for different countries and how currencies are formatted there.

WordPress: 4.1
CMB2: 2.0.1

**Comment by jtsternberg** [comment] 2015-02-09 15:22
I tried to duplicate your issue by adding number field, and saving the value `10`, and as you said, it saves/displays as `10.00`. But when I save the field again, it retains the `10.00` value. I have not seen it go to `1.000.00`. Can you please be more specific with your steps to reproduce the issue?

**Comment by YourMark** [comment] 2015-02-09 18:46
I've added the field like this:

```
$meta_boxes['gig_details'] = array(
    'id'            => 'gig_details',
    'title'         => __( 'Gig details', 'hdln' ),
    'object_types'  => array( 'gigs', ), // Post type
    'context'       => 'normal',
    'priority'      => 'default',
    'show_names'    => true, // Show field names on the left
    // 'cmb_styles' => false, // false to disable the CMB stylesheet
    // 'closed'     => true, // Keep the metabox closed by default
    'fields'        => array(
		array(
		    'name'    => __( 'Entrance', 'hdln' ),
		    'id'      => $prefix . 'entrance',
		    'type'    => 'radio_inline',
		    'options' => $this->entrance,
		),
		array(
		    'name' => __( 'Fee', 'hdln' ),
		    'id' => $prefix . 'gig_fee',
		    'type' => 'text_money',
		    'before_field' => '&euro;',
		    'show_on_cb' => array( $this, 'show_fee_field' ),
		),
    ),
);
```

If I create a new post, the field contains 0.00 as value.
![optreden_aanpassen_ _headline_ _wordpress](https://cloud.githubusercontent.com/assets/1590375/6112687/496272b8-b092-11e4-8c93-9d98ceda65f2.png)

If I fill in 10 and save the post, the value becomes 10.00
![optreden_aanpassen_ _headline_ _wordpress](https://cloud.githubusercontent.com/assets/1590375/6112735/83e2e558-b092-11e4-873f-27fd65f91b1c.png)

If I save the post again, it becomes 1.000.00
![optreden_aanpassen_ _headline_ _wordpress](https://cloud.githubusercontent.com/assets/1590375/6112755/9ca35924-b092-11e4-8043-92c5e9cdc13b.png)

Also, if I try to input a value with decimals, such as 10,50 it saves as 10.00 and 10.50 saves as 1.050.00.

**Comment by jtsternberg** [comment] 2015-02-09 19:24
Still can't duplicate your issues. Entering the different values you've suggested all give me what I would expect. I wonder if it's a PHP version issue? Or possibly a WordPress localization issue? The only field paramater I can't duplicate locally is the `show_on_cb` parameter because I don't have the code for the `show_fee_field` callback, but that really shouldn't affect this.

**Comment by YourMark** [comment] 2015-02-09 19:47
Hm, that's weird.

A localization issue could be the problem. If I check $wp_locale my thousandseparator and decimalseparator are both a . (point). I think (pretty sure) for nl_NL that should be a . and a , (point and comma). Locale is set to nl_NL. (checked).

If I disable show_on_cb this problem still occurs and I checked this with my custom theme, but also with twentyfifteen.

If I check the function 'text_money' in CMB2_Sanitize.php on line 173  and I output $value on line 185 first and then on 187, so just before and just after the number formatting, I get the following:

string '10.00' (length=5)
string '1.000.00' (length=8)

What happens is that in 10.00 the . is removed by the search and replace and then 10.00 becomes 1000. So ten becomes a thousand. I'm guessing this is where it goes wrong.

I'm not sure, but isn't it better to save the number as a float and let the localization take place at the output?

**Comment by JvanderHeide** [comment] 2015-03-05 04:03
+1 :+1:

**Comment by nelero** [comment] 2016-06-29 07:35
same here !
when locale is not english (French for example), problem with comma and point occurs when resaving text_money value

**Comment by jtsternberg** [comment] 2016-06-29 16:15
If anyone can provide exact duplication instructions, I can try to test. (I've never actually changed the WP locale 😊 )

**Comment by nelero** [comment] 2016-07-06 18:52
instead, you'd better use localconv to find wich symbol to sanitize and return
with localeconv http://php.net/manual/en/function.localeconv.php , you can get an associative array with all the details about the current locale.
Keys you need to focus : 
decimal_point
thousands_sep
and/or
currency_symbol
mon_decimal_point
mon_thousands_sep

with this (instead of "point" and "comma" hard coded) you should sanitize successfully a number and fix this bug ...

**Comment by bradp** [comment] 2017-04-03 20:33
Closing due to no movement here. Feel free to re-open if needed.

**Closed by bradp** 2017-04-03 20:33 UTC
