### ISSUE TITLE
Override the field value

### ISSUE THREAD

**Issue by vasikgreif** [WebDevStudios/CMB2#745] opened 2016-09-22 10:51 UTC
I have a dropdown with posts from my custom post type. On post save, I'm saving the dropdown value as post parent_id. I'd like to get that value back, instead of saving the value as post meta. 

Is there a way to  do this?

**Comment by jtsternberg** [comment] 2016-09-22 13:20
Try using the 'escape_cb' field parameter to determine the value that is returned/displayed.

**Comment by vasikgreif** [comment] 2016-09-22 14:02
Thanks, but the value will still be saved as post meta, won't it?

**Comment by jtsternberg** [comment] 2016-09-22 14:05
If you want to re-channle the saving, use the 'sanitization_cb' parameter, or one of the filters.

**Comment by tw2113** [comment] 2016-09-22 15:07
@vasikgreif perhaps a better idea of what you're trying to achieve here would help us out and point to the best option.

**Comment by vasikgreif** [comment] 2016-09-22 18:10
Basically I have a meta box with a dropdown 

```
        $prefix = '_mw_';

        /**
         * Initiate the metabox
         */
        $cmb = new_cmb2_box( array(
            'id'            => 'opportunity_details',
            'title'         => __( 'Opportunity details', 'mw' ),
            'object_types'  => array( 'mw-crm-opportunity', ), // Post type
            'context'       => 'normal',
            'priority'      => 'high',
            'show_names'    => true, // Show field names on the left

        ) );

        $cmb->add_field( array(
            'name'       => __( 'Contact', 'mw' ),
            'id'         => $prefix . 'contact',
            'type'       => 'select',
            'options'   => mw_post_type_dropdown_args('mw-crm-contact')
        ) );
```

The dropdown options are just array of posts ID's and name

```
function mw_post_type_dropdown_args($post_type) {
    $args = array(
        'post_type' => $post_type,
        'posts_per_page' => -1
        );
    $query = new WP_Query($args);
    $posts = $query->get_posts();
    wp_reset_query();

    return wp_list_pluck($posts,'post_title','ID');
}
```

When I save the post, I need to set the selected dropdown value as the post_parent, when I reload page, I need to get the value again (like `$post->post_parent`). 

I would like to avoid saving the value as postmeta altogether, as that is not needed for my application.

Hope this makes more clear what I'm trying to achieve.

**Comment by tw2113** [comment] 2016-09-22 18:36
If I'm following correctly, you're essentially making your own "Select post parent" field. The `mw_post_type_dropdown_args()` function will provide the potential parents. Once one is selected, and the post is published/saved, the selected ID needs to be set as the parent of the post being edited. The selected value also needs to be used to select the "selected" item in the dropdown afterwards. All of this, without actually saving anything to the meta field.

Does it sound like I have a good grasp of what you're aiming for?

**Comment by vasikgreif** [comment] 2016-09-22 18:44
Exactly

**Comment by tw2113** [comment] 2016-09-22 19:15
For the setting of the parent ID, I believe this filter will be useful for you: https://github.com/WebDevStudios/CMB2/blob/trunk/includes/CMB2_Field.php#L290-L324

This should provide a good start, though you'll want to find a way to do this conditionally based on field ID.

```
function my_cmb2_set_post_parent( $override, $args, $field_args, $object ) {
	// Grab the provided meta value
	$tobeparent = (int) $args['value'];
	// Grab the post being edited.
	$futurechild = $args['id'];

	// Returning this, and not $override will make the update_data() method leave early and not process saving meta at all.
	// Since we're not saving anything here, meta-wise, nothing should be saved.
	return wp_update_post( array( 'ID' => $futurechild, 'post_parent' => $tobeparent ) );
	
}
add_filter( 'cmb2_override_meta_save', 'my_cmb2_set_post_parent', 10, 4 );
```

Alternatively, you could use this for the filter: `cmb2_override_{$a['field_id']}_meta_save` but you'd need to fill in the field ID portion yourself based on your settings. Likely `cmb2_override__mw_contact_meta_save` if I'm not mistaken.

Regarding the fetching for the dropdown, I'd recommend these filters. https://github.com/WebDevStudios/CMB2/blob/trunk/includes/CMB2_Field.php#L224-L260 The arguments are going to be very similar to the hooks above. However, it's going to need to return a value that matches the structure that `mw_post_type_dropdown_args()` returns. Essentially you'd need to fetch a post object for the current post, pick out the post_parent property from it, and return that value in the format that matches.

Hope that helps provide some guidance. I'm not handling all of it, but enough to get you started.

**Comment by tw2113** [comment] 2016-10-31 16:25
Closing as not a bug/enhancement idea, and more general usage support.

**Closed by tw2113** 2016-10-31 16:25 UTC
