### ISSUE TITLE
I want to make a custom css editor using cmb2 but which type of field will i use for it ?

### ISSUE THREAD

**Issue by websumon** [WebDevStudios/CMB2#784] opened 2016-10-30 18:41 UTC
I have build a theme options by smb2. For that i have flowed this link:  https://github.com/WebDevStudios/CMB2-Snippet-Library/tree/master/options-and-settings-pages
![9df6af079fac49d9aaf9fead60a6aa7e](https://cloud.githubusercontent.com/assets/8939556/19838884/7a5d22e0-9f02-11e6-9beb-5f4686878667.png)
and i want to build something like this css editor but which type of field will i use for it ?

**Comment by tw2113** [comment] 2016-10-30 19:44
Standard textarea sounds like a solid option to me.

**Comment by websumon** [comment] 2016-10-31 02:51
I have created it by 'type'    => 'textarea_code', is it correct way ? has it another better way ?

`$cmb->add_field( array(
	'name'    => __( 'Custom Style CSS', 'prefix' ),
	'desc'    => __( 'Add Your Custom CSS Styles', 'prefix' ),
	'id'      => 'my_custom_editor',
	'type'    => 'textarea_code',
) );`

**Comment by tw2113** [comment] 2016-10-31 03:00
I think textarea_code includes some `<pre>` tags, which may not be what you want, since you're not intending for this to be displayed to a user.

**Comment by tw2113** [comment] 2016-10-31 16:15
Closing as not a bug/enhancement idea for CMB2. You can still comment afterwards if necessary.

**Closed by tw2113** 2016-10-31 16:15 UTC
