### ISSUE TITLE
'show_option_none' not documented

### ISSUE THREAD

**Issue by a00andos** [WebDevStudios/CMB2#889] opened 2017-03-21 14:00 UTC
Hi!

I just would like to point out that the 'show_option_none' on the taxanomy-* fields are not mentioned in the documentation. I was googling for a solution and ended up on an issue concerning 'show_option_none'.

**Comment by jtsternberg** [comment] 2017-03-21 15:41
Thanks for the heads up. It is actually documented in the Field Types page ([here](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#radio) and [here](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#select)), but should also be added to the [Field Parameters](https://github.com/WebDevStudios/CMB2/wiki/Field-Parameters) page.

As it is a wiki, please feel free to contribute/update that documentation.

**Comment by bradp** [comment] 2017-04-03 19:26
Not a bug, closing.

**Closed by bradp** 2017-04-03 19:26 UTC
Labels: Documentation
