### ISSUE TITLE
cmb2_get_metabox_form output buffering may not be properly clearing

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/CMB2#366] opened 2015-06-27 21:08 UTC
Getting repeated forms when fetching data within a loop.

```php
$postIDs  = array(4, 820, 821); //any valid IDs really
$forms     = array();
foreach( $postIDs as $postID ) {
	$forms[] = cmb2_metabox_form("foobar", $postID, array( "cmb_styles" => false, "form_format" => "", "echo" => ""));
}
print_r($forms);
```
The results of the print_r() are the form for the first ID multiple times. It's my belief that the following 2 lines are the bottleneck, but am not sure personally how to get around it.

```php
$form = ob_get_contents();
ob_end_clean();
```

**Comment by jtsternberg** [comment] 2015-07-15 14:11
Closing as duplicate of #354

**Closed by jtsternberg** 2015-07-15 14:11 UTC
Labels: bug, Helper Functions
