### ISSUE TITLE
Repeatable group saving empty

### ISSUE THREAD

**Issue by markduwe** [WebDevStudios/CMB2#847] opened 2017-01-26 20:26 UTC
### Expected Behavior:
Not filling anything in - nothing gets saved

### Actual Behavior:
Not filling anything in - something gets saved

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):
1.  create new page and save
2.  
```php 
$entries = get_post_meta( $page_id, 'sideimages', true );
print_r($entries);
```
Shows
```php 
Array ( [0] => Array ( [img_id] => 0 ) )
```
on newly saved page, but on an old page that existed before the meta box was created and hasn't been updated since, nothing shows.

### CMB2 Field Registration Code:
```php
	add_action( 'cmb2_admin_init', 'page_meta' );
	function page_meta() {
		$prefix = '_page_';
		$cmb_page = new_cmb2_box( array(
			'id'			=> 'page',
			'title'			=> 'Page Side Images',
			'object_types'	=> array( 'page' ),
		) );
		$page_images = $cmb_page->add_field( array(
			'id'			=> 'sideimages',
			'type'			=> 'group',
			'description'	=> __( 'Side images for the page', 'ch' ),
			'options'		=> array(
				'group_title'   => __( 'Image {#}', 'ch' ),
				'add_button'	=> __( 'Add Another Image', 'ch' ),
				'remove_button' => __( 'Remove Image', 'ch' ),
				'sortable'	  => true, // beta
			),
		) );
		$cmb_page->add_group_field( $page_images, array(
			'name'			=> 'Image',
			'id'			=> 'img',
			'type'			=> 'file',
		) );
		$cmb_page->add_group_field( $page_images, array(
			'name'			=> 'Image Caption',
			'id'			=> 'caption',
			'type'			=> 'text',
		) );
	}
```

**Comment by tw2113** [comment] 2017-01-26 20:31
Curious if this is related to #845 in some way. Both are very similar.

**Comment by markduwe** [comment] 2017-01-26 21:35
Could be. 
This is along the lines of an empty field saving on page update, so that 
```php
if($entries != '') {
// do something
} else {
// something else 
}
```
Never fires the 'something else' part.

**Comment by tw2113** [comment] 2017-01-27 22:17
So, I believe this comes down to the fact that at the point of creation, the metaboxes are populated enough that meta data is able to be saved, even on publish. Possible that the autosave contributes as well. What gets saved is the structure used to store a group of fields. The moment I hit "update" on an existing page, the `a:1:{i:0;a:1:{s:6:"img_id";i:0;}}` value did get saved.

So, it's essentially a case of "invisible" content in place to be saved as meta.

Regarding the last part with an if check, `$entries` isn't technically empty, or an empty string. It's an array with a single index holding an array of "img_id" for the key, and int 0 for the value, until you save anything. The "img_id" looks to be the attachment ID, 0 by default. Once you save an image, it'll use that image's attachment ID.

For display in these types of cases, something like the following should work, with a bit of customization for display:

```

$entries = get_post_meta( $page_id, 'sideimages', true );
if ( is_array( $entries ) ) {
	foreach ( $entries as $entry ) {
		if ( is_array( $entry ) ) {
			foreach( $entry as $item ) {
				printf( '<div><img src="%s" />%s</div>', $item['img'], $item['caption'] );
			}
		}
	}
}
```

**Comment by jtsternberg** [comment] 2017-01-28 03:42
Pretty sure this is a duplicate of #721, which was addressed in https://github.com/WebDevStudios/CMB2/commit/2bf2b7063bf6f3a63911c57ba148e800f1b8c59e. Are you sure you tested with the trunk branch?
That is why the issue template contains the text, "I have confirmed I can reproduce this issue on the trunk branch". But if you ARE able to reproduce on the trunk branch, let us know.

**Comment by bradp** [comment] 2017-04-03 20:25
Closing due to no movement here. Feel free to re-open if applicable.

**Closed by bradp** 2017-04-03 20:25 UTC

**Comment by feroxy** [comment] 2018-03-20 17:27
I'm running into this problem again in 2.3.0
Updating a page saves an empty group entry
