### ISSUE TITLE
Using Composer's autoload

### ISSUE THREAD

**Issue by bignall** [WebDevStudios/CMB2#741] opened 2016-09-16 01:04 UTC
### Expected Behavior:

`composer dump-autoload` should include CMB2 

### Actual Behavior:

CMB2 is not included in composer's autoload

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1.  composer install cmb2

It downloads and installs cmb2 as it should, but the autoload doesn't load it.

**Comment by jtsternberg** [comment] 2016-09-16 06:28
Closed as duplicate of #198. Please see the relevant discussion there (and the linked commit).

**Closed by jtsternberg** 2016-09-16 06:28 UTC
