### ISSUE TITLE
Incorrect Storing of Timezones

### ISSUE THREAD

**Issue by curtismchale** [WebDevStudios/CMB2#227] opened 2015-03-04 21:43 UTC
``` php
        /** The updates for meetings */
        $meta_boxes['meeting_info_metabox'] = array(
            'id'            => 'meeting_info',
            'title'         => __( 'Meeting Information', 'cmb2' ),
            'object_types'  => array( 'page', ), // Post type
            'context'       => 'normal',
            'priority'      => 'high',
            'show_names'    => true, // Show field names on the left
            // 'cmb_styles' => false, // false to disable the CMB stylesheet
            // 'closed'     => true, // Keep the metabox closed by default
            'fields'        => array(
                array(
                    'name' => 'Time zone',
                    'id'   => $prefix . 'timezone',
                    'type' => 'select_timezone',
                ),
                array(
                    'name'              => __( 'Next Meeting', 'cmb2' ),
                    'desc'              => __( 'When is the next meeting', 'cmb2' ),
                    'id'                => $prefix . 'next_meeting',
                    'type'              => 'text_datetime_timestamp',
                    'timezone_meta_key' => $prefix . 'timezone',
                ),
                array(
                    'name'       => __( 'Next Meeting Topic', 'cmb2' ),
                    'desc'       => __( 'What is the topic of the next meeting', 'cmb2' ),
                    'id'         => $prefix . 'next_meeting_topic',
                    'type'       => 'text',
                ),
                array(
                    'name'       => __( 'Email Update to Members', 'cmb2' ),
                    'desc'       => __( 'Emails the latest meeting update to members', 'cmb2' ),
                    'id'         => $prefix . 'email_update',
                    'type'       => 'sfn_submit',
                ),
                array(
                    'id'          => $prefix . 'meeting_repeat_group',
                    'type'        => 'group',
                    'description' => __( 'Past Meeting Information', 'cmb' ),
                    'options'     => array(
                        'group_title'   => __( 'Entry {#}', 'cmb' ), // since version 1.1.4, {#} gets replaced by row number
                        'add_button'    => __( 'Add Another Meeting', 'cmb' ),
                        'remove_button' => __( 'Remove Meeting', 'cmb' ),
                        'sortable'      => true, // beta
                    ),
                    // Fields array works the same, except id's only need to be unique for this group. Prefix is not needed.
                    'fields'      => array(
                        array(
                            'name'              => 'Meeting Date',
                            'id'                => 'meeting_date',
                            'type'              => 'text_datetime_timestamp',
                            'desc'              => 'When was this meeting held?',
                        ),
                        array(
                            'name' => 'Minutes Link',
                            'id'   => 'minitues_link',
                            'type' => 'text_url',
                            'desc' => 'Provide link to the meeting minutes',
                            // 'repeatable' => true, // Repeatable fields are supported w/in repeatable groups (for most types)
                        ),
                        array(
                            'name' => 'Meeting Links',
                            'id'   => 'present_link',
                            'type' => 'wysiwyg',
                            'desc' => 'Any other links or headings that the meeting generated',
                            //'repeatable' => true,
                        ),
                    ),
                ),

            ),
        );
```

Given the above array, when I save the `$prefix . 'next_meeting'` field for March 5th at 10am and the Timezone field is set to Vancouver the Unix timestamp I get is `1425520800` which corresponds to March 5th 2:00 GMT which is 6pm Pacific (Vancouver).

If I remove the timezone settings then it saves it assuming the time setting is GMT which gets me 2am Pacific.

**Comment by joeljoeljoel** [comment] 2016-03-10 17:34
I'm also experiencing this issue.  If I enter a date/time as March 17, 10PM in New York and save the post, the date time is March 17, 9pm.  Every time I save the post, the time falls back by one hour.

I believe the issue is the timezone offset is being miscalculated in areas that observe Daylight Savings Time.  For example, in the Eastern timezone the offset today (March 10) is 5 hours but next Thursday (March 17) the offset will be 4 hours.

I think the source of the issue is here:
https://github.com/WebDevStudios/CMB2/blob/c1bd09f9fdf1b4ca5ef5d10a31bcfc74db9a3e06/includes/CMB2_Utils.php#L88

The current date is being used to calculate the offset but the date that's being entered in the input should probably be used instead.

**Comment by jazbek** [comment] 2016-08-15 19:51
I just ran into this problem as well, that line is definitely the problem. 

The date being saved to the database needs to be specifically passed to date_create(), or else it uses now. Now might not be during daylight savings, but the date being displayed is, in which case the offset returned today would not be correct.

**Comment by jtsternberg** [comment] 2016-08-15 20:34
Would either of you care to open a PR? Sounds like you have a decent handle on the issue.

**Comment by jtsternberg** [comment] 2016-08-15 20:52
Please test https://github.com/WebDevStudios/CMB2/pull/708

**Comment by joeljoeljoel** [comment] 2016-08-16 13:37
@jtsternberg The fix looks good to me.

I tested dates before March 13 (the start of DST), after November 6 (the end of DST) and dates in between and the time was unaffected.

**Comment by bradp** [comment] 2017-04-03 20:59
Looks like this is now fixed. Going to close this one. Feel free to re-open if there are future issues.

**Closed by bradp** 2017-04-03 20:59 UTC
Labels: bug
