### ISSUE TITLE
Load through ajax a form

### ISSUE THREAD

**Issue by fakeartist** [WebDevStudios/CMB2#882] opened 2017-03-16 12:36 UTC
Hi. Is it possible to load a cmb2 form with ajax?

For example, throught the click of one button, I want to load a specifix cmb2 form using cmb2_metabox_form function.

**Comment by tw2113** [comment] 2017-03-16 13:52
No way that I personally know of, but others may have a better idea.

**Comment by bradp** [comment] 2017-04-03 19:26
Not a bug, closing.

**Closed by bradp** 2017-04-03 19:26 UTC
