### ISSUE TITLE
Drop down list with all Revolution Slider

### ISSUE THREAD

**Issue by br0k3n** [WebDevStudios/CMB2#771] opened 2016-10-15 11:37 UTC
Hi guys, is there a way to get a drop down list of all revolution sliders created to use as option?

Thanks in advance :)

**Comment by tw2113** [comment] 2016-10-15 17:37
I'm sure there must be a way somehow, but that's more of a question for Revolution Slider support, more than our support. Not sure if they populate their own dropdown menus at all, or if they just have each be a post type, for example, but those would be good places to start.

**Comment by tw2113** [comment] 2016-10-31 16:19
Closing as not a bug/enhancement idea.

**Closed by tw2113** 2016-10-31 16:19 UTC

**Comment by themevan** [comment] 2017-09-16 16:56
Try the following codes

if ( class_exists( 'RevSlider' ) ) {
    $rev_slider = new RevSlider();
    $sliders = $rev_slider->getAllSliderAliases();
} else {
    $sliders = array();
}
