### ISSUE TITLE
[After update] Repeatable groups, all items numbered as #1 in admin

### ISSUE THREAD

**Issue by kirillbunin** [WebDevStudios/CMB2#315] opened 2015-05-06 23:10 UTC
I'm not exactly sure if the problem is in the plugin, or in my sites, but, on 3 — 4 different domains and different templates, after auto updating this through WordPress this issue occure.

When i add items to repeatable group and save, I get all items in group numbered as #1. `data-iterator` attribute changes accordingly, on `.cmb-row` wraps. Neither does it break working with data. Seems like simple UI error.

**Comment by jtsternberg** [comment] 2015-05-06 23:40
This is a duplicate of #310.

**Closed by jtsternberg** 2015-05-06 23:40 UTC
