### ISSUE TITLE
Any way to add meta box tabs?

### ISSUE THREAD

**Issue by ashawkat** [WebDevStudios/CMB2#156] opened 2015-01-23 14:16 UTC
Is there any way to use the fields in different tabs in post types. This would be really a good thing if the tabs option comes along with the framework. Please let  me know soon as I want a solution please.

**Comment by jtsternberg** [comment] 2015-01-23 14:36
This is a duplicate of #5. There is not currently a built-in way.

**Closed by jtsternberg** 2015-01-23 14:36 UTC
