### ISSUE TITLE
Featured image

### ISSUE THREAD

**Issue by jrswebdesign** [WebDevStudios/CMB2#830] opened 2017-01-09 10:43 UTC
### Expected Behavior:

Hello, is there a way to show featured images?
On my default blogpost page there is a option to set featured image
On my CMB2 page not.
How can i fix this?

**Comment by tw2113** [comment] 2017-01-09 16:03
If the "CMB2 page" you refer to is a custom post type editor screen, then having it registered with featured image support would be the way to go there. Not something specific to CMB2. If it's an options page, then you'd just need to use one of the file field types to set up something similar to that functionality.

**Comment by tw2113** [comment] 2017-01-09 16:04
Closing the issue as it's not a bug report, but you can still comment on it afterwards.

**Closed by tw2113** 2017-01-09 16:04 UTC
