### ISSUE TITLE
Radio Inline Field

### ISSUE THREAD

**Issue by kajdzo** [WebDevStudios/CMB2#713] opened 2016-08-17 13:40 UTC
Hi guys, first of all thanks for awesome library. 
With that said I have question.
I've been using WP Ver. 4.5.3 until this morning after update release I've updated to 4.6.
CMB2 Version 2.2.2.1

I have couple radio_inline fields with 3 options per field and whenever I change the option and hit save it goes back to a default state. The value  is saved but in meta-box it is always in default position. 

The problem exist in both WP versions.

This is my field declaration:

```php
 $title_meta->add_field(array(
            'name'    => __('Title Area Skin', 'theme-slug'),
            'id'      => $prefix . 'skin',
            'type'    => 'radio_inline',
            'options' => array(
                '0'       => __('Dark', 'theme-slug'),
                '1'       => __('Light', 'theme-slug'),
                'inherit' => __('Inherit from Theme Options', 'theme-slug')
            ),
            'default' => 'inherit'
        ));
```
Any help is welcome. 
Greetings

![before update](https://cloud.githubusercontent.com/assets/10382570/17738218/add405dc-6490-11e6-9808-2f28228cab50.png)
![after update](https://cloud.githubusercontent.com/assets/10382570/17738219/add45280-6490-11e6-9ddf-1080b4b42d18.png)

**Comment by jtsternberg** [comment] 2016-08-17 14:18
Thank you for reporting. It's because of the '0' value, but should be fixed in trunk (will be in the next release). In the future, it would be super helpful to us as maintainers if before opening an issue, you were able to test and confirm the issue in the trunk (development) branch. You can see the related issue here: #668

**Comment by jtsternberg** [comment] 2016-08-17 14:19
Closing, as I believe this to be fixed, but if you're still able to reproduce on trunk, please let us know.

**Closed by jtsternberg** 2016-08-17 14:19 UTC

**Comment by kajdzo** [comment] 2016-08-19 07:46
Thank you guys for your help. The post that you pointed me to helped me. Sorry for not checking previous posts.
