### ISSUE TITLE
Drag and drop functionality for repeater

### ISSUE THREAD

**Issue by zeljkorad** [WebDevStudios/CMB2#682] opened 2016-07-06 15:11 UTC
Hi guys,

Great framework for custom meta boxes. Love it. I have one question. I am wondering is it possible to implement drag and drop sorting of elements for repeatable group fields?

**Comment by tnorthcutt** [comment] 2016-07-26 14:50
Closing as duplicate of https://github.com/WebDevStudios/CMB2/issues/155

**Closed by tnorthcutt** 2016-07-26 14:50 UTC
