### ISSUE TITLE
Broken layout when context set to after_title

### ISSUE THREAD

**Issue by allysonsouza** [WebDevStudios/CMB2#880] opened 2017-03-14 21:00 UTC
### Expected Behavior:
Add meta box after title without breaking other meta boxes.

### Actual Behavior:
When you add a meta box to context `after_title` or `before_permalink` the side meta boxes are pushed down.

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):
1.  Create a meta box with context `after_title` or `before_permalink`

### CMB2 Field Registration Code:

```
$cmb = new_cmb2_box( array(
	'id'            => 'my_meta_box',
	'title'         => 'Title',
	'object_types'  => array( 'post' ),
	'context'       => 'after_title',
	'priority'      => 'normal',
) );

$cmb->add_field( array(
    'name'    => 'Field',
    'id'      => $prefix . 'my_id',
    'type'    => 'text',
) );
```

**Comment by tw2113** [comment] 2017-03-14 21:43
Can confirm, at least with given basic parameters. looks to be a mix of float and width issues.

![screen shot 2017-03-14 at 4 42 54 pm](https://cloud.githubusercontent.com/assets/484075/23923619/53f3d65c-08d5-11e7-8087-8875ee6dce4f.png)

**Comment by jtsternberg** [comment] 2017-03-14 22:13
This is a duplicate of #871. It is a confirmed bug, and we'll be addressing soon.

**Closed by jtsternberg** 2017-03-14 22:13 UTC
