### ISSUE TITLE
2 selected items on certain conditions

### ISSUE THREAD

**Issue by janw-oostendorp** [WebDevStudios/CMB2#668] opened 2016-06-20 09:57 UTC
The following select gives the following result:

```
$metabox->add_field( array(
    'name'             => __( 'Gold value' ),
    'id'               => self::$prefix . 'value',
    'type'             => 'select',
    'default'          => 'no_item',
    'options'          => array(
        'no_item' => __( 'Not an Item' ),
        0         => __( 'No value' ),
        100       => 100,
        200       => 200,
    ),
) );
```
The html output:

````
<select class="cmb2_select" name="_card_value" id="_card_value">
	<option value="no_item" selected="selected">Not an Item</option>
	<option value="0" selected="selected">No value</option>
	<option value="100">100</option>
	<option value="200">200</option>
</select>
````

Both first two options are _selected_.

The fix:
In the file `public_html/content/plugins/cmb2/includes/CMB2_Types.php:226`

````
//if ( $value == $opt_value ) {
if ( $value === $opt_value ) {
````
PHP thinks (0 == 'string') >> bolean(true)

Can this be fixed?

**Comment by jtsternberg** [comment] 2016-07-01 14:29
I don't think this is still an issue. Can you check the most recent version?

**Comment by janw-oostendorp** [comment] 2016-07-07 06:58
Nope still here. The problem moved to `plugins/cmb2/includes/types/CMB2_Type_Multi_Base.php:67`

**Comment by tw2113** [comment] 2016-08-02 15:56
@jtsternberg I can confirm this is still in place with the master branch.

The issue ends up being the numeral zero above. 

```
if ( $value == $opt_value ) {} // Evaluates to true. $value is "no_item", $opt_value is integer 0.
```
https://blog.josephscott.org/2012/03/12/why-php-strings-equal-zero/

Honestly the best approach here would probably not use numeral 0 for values, but strict type checking on this would also help mitigate edge case issues:
```
if ( $value === $opt_value ) {
```

**Comment by jtsternberg** [comment] 2016-08-02 16:16
This should be fixed with https://github.com/WebDevStudios/CMB2/commit/b7f68222245aee925d556129db88b50707e574dc and https://github.com/WebDevStudios/CMB2/commit/9d9b07851253e178a95f3322ecc272d6b1bc1d6f, but would appreciate confirmation.

**Comment by tw2113** [comment] 2016-08-02 16:29
This alone should be the solver https://github.com/WebDevStudios/CMB2/commit/b7f68222245aee925d556129db88b50707e574dc#diff-987cba9503bafd086dc24438f136a7bdR93

However, would love for @janw-oostendorp to confirm for his usage.

**Comment by janw-oostendorp** [comment] 2016-08-03 10:15
@tw2113 
I tested the diff it doesn't work :(

The `$value` (which comes from the database) is a string. But the field values are integers.

**Comment by tw2113** [comment] 2016-08-03 14:07
Not quite sure why this would be failing for you suddenly, since the diff spot I pointed out is the exact same solution you suggested at the end of the initial issue description.

Also read https://blog.josephscott.org/2012/03/12/why-php-strings-equal-zero/ for why it was evaluating to true in the first place. Thanks PHP.

**Comment by jtsternberg** [comment] 2016-08-03 15:26
@janw-oostendorp you tested the diff, or you tested trunk? @tw2113 was mistaken in that that diff was not the complete solution.

**Comment by janw-oostendorp** [comment] 2016-08-03 16:46
I had a up to date CMB2 in WordPress and manually applied the DIFF.
I'll test trunk.

**Comment by janw-oostendorp** [comment] 2016-08-03 17:00
Trunk works.  
Yaay

**Comment by tw2113** [comment] 2016-08-03 17:18
Yay

**Comment by tw2113** [comment] 2016-08-03 17:18
Marking closed, since we have multiple confirmations.

**Closed by tw2113** 2016-08-03 17:18 UTC
