### ISSUE TITLE
Possibility of setting a default currency symbols for text_money

### ISSUE THREAD

**Issue by jcchavezs** [WebDevStudios/CMB2#326] opened 2015-05-21 10:31 UTC
I have realized that as a developer you can not manage to set a default currency_symbol for the text_money field, it is always *$*. The easiest (but weird in a way) is to make a loop and add the argument 'before_field' but there is a difficult in text_money fields inside 'group' fields.

I think we can solve it with the addition of the the code below inside the function _set_field_defaults.

```
if( $args['type'] === 'text_money' ) {
	$args['before_field'] = apply_filters( 'cmb2_text_money_before_field_filter', ( isset($args['before_field']) ? $args['before_field'] : '$' ), $this );
}
```

*Note:*

I thought on adding the feature of detecting the currency based on wp_locale but it is not the best way when it comes to multilanguage sites.

By the way, one can get the currency according to the location with the functions:

```
if( !defined( 'CMB2_NUMBER_LOCALE' ) ) {
	define( 'CMB2_NUMBER_LOCALE', get_locale() );
}

[...]

private function get_text_money_before_field() {
	if(!class_exists('NumberFormatter')){
		return '$';
	}

	$numberFormatter = new NumberFormatter( CMB2_NUMBER_LOCALE, NumberFormatter::CURRENCY );

	return $numberFormatter->getSymbol( NumberFormatter::CURRENCY_SYMBOL );
}
```
I think that the currency detection is out of the scope of this plugin so it must be setted somewhere else..

**Comment by jtsternberg** [comment] 2015-07-29 13:57
you simply need to specify the 'before_field' parameter to whatever currency you need. There is no reason to add the filter. if you set the 'before_field' parameter, it uses that instead of the '$'.

**Comment by jcchavezs** [comment] 2015-07-29 14:29
So no way to set it up globaly like date format?

**Comment by jtsternberg** [comment] 2015-07-29 21:41
Unfortunately not.. The problem is, if you change it globally and the user has another plugin w/ CMB2 bundled and it expects/needs $ values, your filter could mess with that and cause their data to look/be incorrect. Make sense?

**Comment by jcchavezs** [comment] 2015-07-29 21:57
I would expect to have a global currency for money. I do not see a conflict
with other plugins and we should also consider that we are not talking
about overriding all the text_money fields, we are talking about the
default symbol in the backend which is not something relevant for the front
end as in the end you will format the value in the front end in the way you
want (when it comes to decimals, currency and etc.)

I hope you reconsider this issue.
ons. 29. jul. 2015 kl. 23.41 skrev Justin Sternberg <
notifications@github.com>:

> Unfortunately not.. The problem is, if you change it globally and the user
> has another plugin w/ CMB2 bundled and it expects/needs $ values, your
> filter could mess with that and cause their data to look/be incorrect. Make
> sense?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebDevStudios/CMB2/issues/326#issuecomment-126105079>.
>
-- 
*José Carlos Chávez*
Norge: (+47) 40428839
España: (+34) 657788435
Perú: (+51) 708-5422 Anexo 918

https://github.com/jcchavezs

**Comment by jtsternberg** [comment] 2015-07-30 00:11
> I do not see a conflict with other plugins

The expected default is $. If you change that via a filter, you will break the expected behavior. If I had fields registered in my plugin like:

```php
$cmb_demo->add_field( array(
	'name' => __( 'Amount in U.S.', 'cmb2' ),
	'id'   => $prefix . 'us_amount',
	'type' => 'text_money',
) );

$cmb_demo->add_field( array(
	'name' => __( 'Amount in G.B.', 'cmb2' ),
	'id'   => $prefix . 'gb_amount',
	'type' => 'text_money',
	'before_field' => '£', // override '$' symbol if needed
) );
```

And you filtered it to be € or something, then the us_amount field would display a € instead of $.

> we should also consider that we are not talking about overriding all the text_money fields

That's exactly what your proposed `cmb2_text_money_before_field_filter` filter would do.

**Comment by jcchavezs** [comment] 2015-07-30 05:35
> And you filtered it to be € or something, then the us_amount field would display a € instead of $.

I would expect that a developer pass the currency symbol also for the default (by that time) currency because I can not be sure when the library will change. It is like not using **get_the_date** function because my date format is the same as the system's default or not using **__** or **_e** if I expect my site to be in English.

> That's exactly what your proposed cmb2_text_money_before_field_filter filter would do.

Yes, I was just remarking that.

**Comment by jtsternberg** [comment] 2015-07-30 15:35
> I would expect that a developer pass the currency symbol also for the default (by that time) currency 

Why would they pass it if the default is what they expect and want?

> because I can not be sure when the library will change.

CMB2 holds the same backwards-compatibility standards as WordPress. A user SHOULD be sure the library will not break his code in future versions. That is why CMB2 has a built-in handler to be sure only the newest version is loaded. it CAN do that because new features should not break existing functionality.

**Comment by jtsternberg** [comment] 2016-08-16 18:32
Based on the [back-compatibility concerns](https://github.com/WebDevStudios/CMB2/issues/326#issuecomment-126105079) with the suggested filter, I'm closing this issue.

**Closed by jtsternberg** 2016-08-16 18:32 UTC
Labels: enhancement
